INSERT INTO principles (name, description) 
VALUES 
('Practice Introspection', 'The answers you seek are in the silence you avoid.'),
('Confront Your Flaws', 'Your greatest opponent is your own worst nature.'),
('Recognize Projections', 'What you hunt in others, you hide in yourself.'),
('Define Your Perspective', 'Frame your world, or it will be framed for you.'),
('Clarify Your Focus', 'Your aim determines what you see.'),
('Embrace Diverse Thinking', 'No two minds are wired the same.'),
('Find Opportunity in Problems', 'One man''s problem is another man''s purpose.'),
('Find Value in Flawed Ideas', 'A broken clock is still right twice a day. Any argument, even with wrong bounds, might hold a kernel of truth.'),
('Challenge Willful Ignorance', 'There are none so blind as those who will not see.'),
('Trust Your Recognition', 'Wisdom is not a lesson, it is recognition.'),
('Observe Your Emotions', 'Emotions are a guide, not the truth. Log them as signals, not as facts.'),
('Pursue Truth Actively', 'Truth is a beautiful adventure.'),
('Choose Your Commitments', 'You cannot choose *if* you worship, only *what* you worship. Be intentional about your ultimate concerns.'),
('Leverage Your Origins', 'Don''t forget where you came from. This is your one advantage.'),
('Practice Focused Commitment', 'To grow a mighty oak, you must choose not to plant a hundred other seeds.'),
('See the Whole System', 'Play the board, not the pieces. Look at the entire system, not just the immediate players.'),
('Prioritize Long-Term Gain', 'Today''s drink is tomorrow''s hangover. Weigh the second and third-order consequences of your choices.'),
('Redesign the System', 'Don''t change the player, change the game. Focus on changing the rules and environment.'),
('Choose Your Battles', 'Play a game you can win. Focus your energy where you have a natural advantage or a clear path.'),
('Analyze Incentives', 'Incentives, incentives, incentives. Understand what motivates yourself and others.'),
('Embrace Constraints', 'Constraint is the mother of creativity. Use limitations as a catalyst for new solutions.'),
('Prune Your Commitments', 'Tend your garden; prune ruthlessly. Strategically remove projects, habits, and relationships that no longer serve you.'),
('Practice Self-Acceptance', 'You are the treasure you have been digging for. Stop searching and start being.'),
('Find Joy in the Process', 'The joy you seek in the future is brewed in the coffee you''re holding now.'),
('Appreciate Today', 'Today is the ''good old day'' you''ll one day long for.'),
('Act to Reduce Anxiety', 'Action is the antidote to anxiety. When in doubt, take the next small step.'),
('Bias Toward Action', 'A map is not the territory; stop reading and start walking.'),
('Be Specific', 'The world rewards the specific. Vague goals lead to vague results. Define *exactly* what you want.'),
('Focus on Progress, Not Motion', 'Don''t confuse motion with progress. Is this task moving you forward, or just keeping you busy?'),
('Build Consistent Habits', 'Consistency does not guarantee success, but inconsistency guarantees failure.'),
('Ensure Your Tools are Effective', 'An axe that does not chop is just a weight. Audit your systems and habits. If they don''t work, fix or discard them.'),
('Prioritize Exploration', 'Exploration proceeds execution. It''s okay to experiment and fail before you find the right path to execute.'),
('Tackle Big Challenges', 'The biggest dragon hordes the largest treasure. Don''t shy away from the problems that scare you.'),
('Embrace Imperfection', 'Perfection is a direction, not a destination. Focus on iteration, not a flawless final product.'),
('Accept Necessary Losses', 'You must lose some soldiers to win the war. Accept small, strategic failures in service of the larger goal.'),
('Review Your Failures', 'Review the game tape after every loss. When something goes wrong, analyze *why* without judgment.'),
('Build a Toolkit of Knowledge', 'One key opens one door; true knowledge is a key ring. Collect mental models and skills from different fields.'),
('Master the Fundamentals', 'You must understand the rules before you can break them.'),
('Reframe Imposter Syndrome', 'Learn to love imposter syndrome. It''s a sign that you are pushing your boundaries and growing.'),
('Live Unashamedly', 'People are quick to forget, so live the life you want unashamedly. Don''t let fear of judgment hold you back.'),
('Adapt to Reality', 'You cannot command the wind, but you can adjust the sails. Focus on what you can control: your response.');